[package]
name = "vrcx-0-platform"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Host-neutral platform primitives"

[dependencies]
chrono = { workspace = true }
dirs = { workspace = true }
machine-uid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2.workspace = true
specta.workspace = true
thiserror = { workspace = true }
tracing = { workspace = true }
vrcx-0-core = { path = "../core" }
